name: Simple github Workflow

on: [push]

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Run simple shell script
      run: bash simple_script.sh
